[build]
  ignore = "git diff --quiet HEAD^ HEAD src index.html"
  publish = "dist"
  command = "vite build --base=/ --mode prod"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
